### ISSUE TITLE
[Feature Request]Auto-sync every xx seconds?

### ISSUE THREAD

**Issue by samwei12** [EINDEX/logseq-memos-sync#1]
Thanks for your perfect plugin!
Could you add a feature so we can auto-sync memos every xx seconds?
Manually opening the panel to sync is a painful thing :)

**Comment by EINDEX** [comment]
Oh, right now I'm using `refresh` workaround to do this, v1.1.0 support sync data when Logseq init.

The shortcut for macOS is `cmd + R`.

Anyway, I will add this feature soon.

**Comment by EINDEX** [comment]
Add this feature in 2888da46c4f366871224f4ad9c39026e06bfe274 welcome to have a try.

https://github.com/EINDEX/logseq-memos-sync/releases/tag/v1.2.0
