### ISSUE TITLE
The api has been updated to request an adaptation, and the original won't work with light.

### ISSUE THREAD

**Issue by Mydong** [EINDEX/logseq-memos-sync#13]
The api has been updated to request an adaptation, and the original won't work with light.

https://github.com/usememos/memos/tree/main/docs/api

**Comment by EINDEX** [comment]
Thanks for the info, will follow the upgrade.

**Comment by Mydong** [comment]
Thanks

**Comment by EINDEX** [comment]
Fix via f65e067976e591e477d09b229c12b69467dc62c3.

Hope memos did not change API in this way anymore.
