### ISSUE TITLE
Memos Sync Setup Issue (404)

### ISSUE THREAD

**Issue by TatamoChang** [EINDEX/logseq-memos-sync#24]
memos version: v0.13.1
logseq-memos-sync: v1.8.2

memos sync connect server with `/api/v1/memo` , but v0.13.1 provide `/api/memo` instead.

console log on logseq
![image](https://github.com/EINDEX/logseq-memos-sync/assets/5977351/644c37bc-c939-4322-83fc-8b21c9319eb3)

OpenAPI info
![image](https://github.com/EINDEX/logseq-memos-sync/assets/5977351/8f02447d-f9df-4a40-a4b3-222636c70ec0)

**Comment by EINDEX** [comment]
it should just send first request to detect memos version, if this response is not success, sync will fallback to old api.

**Comment by EINDEX** [comment]
Append: 
I do not have a low version of memos currently, If you can fix this, PR is welcome, and I can review it.

And lower memos version may crush my data, If you can buy some coffee for me, I can try to spend some time to fixing this issue.

**Comment by TatamoChang** [comment]
I'll make sure to use the latest version of memos. Thank you!
