### ISSUE TITLE
Can not sync new memos after pinned memo

### ISSUE THREAD

**Issue by TatamoChang** [EINDEX/logseq-memos-sync#25]
Dear logseq-memos-sync Developer,

I want to express my gratitude for creating the logseq-memos-sync tool. It has been a valuable addition to my workflow, helping me keep my memos synchronized effortlessly. However, I have encountered a minor issue that I would like to bring to your attention.

After I pin a memo to the top of my list, I have noticed that any new memos I create do not seem to update as expected. It appears that the synchronization may not be working correctly in this specific scenario.

Once again, thank you for your work on logseq-memos-sync, and I look forward to any improvements or solutions you may provide in the future.

Sincerely,
Jason Chang

**Comment by EINDEX** [comment]
@TatamoChang  how many pinned memos do you have?

**Comment by TatamoChang** [comment]
2 or 3 sometimes.
All memos in api response with key `"pinned": {true|false},` , it defines each memo is pinned or not.

**Comment by EINDEX** [comment]
fixed in new release
