### ISSUE TITLE
不确定是不是0.15.1是不是又更新了，0.15版本上token后还正常，然后0.15.1后，插件就报错了。

### ISSUE THREAD

**Issue by Mydong** [EINDEX/logseq-memos-sync#27]
已经重新安装了插件，填写了新的token，但是还是报错；
![image](https://github.com/EINDEX/logseq-memos-sync/assets/14023137/e8e6063f-5f16-40a5-952c-b3f26f608b93)

**Comment by EINDEX** [comment]
可以给一个 console 的截图吗？

**Comment by Mydong** [comment]
> 可以给一个 console 的截图吗？

感谢回复；

我刚刚想要弄console截图的时候，重新启动了几次。然后，最后一次突然好了，不知道是做了啥，感觉我啥都没有改；

现在是好的状态的截图。【已经解决】，再次感谢作者；

![image](https://github.com/EINDEX/logseq-memos-sync/assets/14023137/69bef581-59f6-4df2-85c8-16dc2b933fbd)

**Comment by EINDEX** [comment]
好的 感谢反馈。 memos 更新总是 breaking change，服务端升级可能会有一些影响。
我这里也有时候抽风但是不能重现就 😢  。
