### ISSUE TITLE
TODO content sync issue

### ISSUE THREAD

**Issue by samwei12** [EINDEX/logseq-memos-sync#5]
TODO show in memos:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/12758352/222938262-0b83b7a0-237c-4291-94b7-3305db7ae5c9.png">

After sync 

![image](https://user-images.githubusercontent.com/12758352/222938314-46350070-2cdf-4b11-825e-84546801372c.png)

![image](https://user-images.githubusercontent.com/12758352/222938315-793bf777-2534-4b7d-a125-c167b9466e32.png)

**Comment by EINDEX** [comment]
You can just use the markdown format `- [ ] todo`  in memos, it will automatically trans to Logseq TODO/NOW depend your preferred todo settings in Logseq.

**Comment by samwei12** [comment]
It works! Thanks
