### ISSUE TITLE
how to enable image sync from memos to logseq?

### ISSUE THREAD

**Issue by Oaklight** [EINDEX/logseq-memos-sync#6]
When content pulled from memos, images within each memo are currently not synced. Will this be supported in the future? If so, when would it possibly be available?

Thanks!

**Comment by EINDEX** [comment]
Hey @Oaklight,

Now is not support memos resource sync, like img, file, etc.

If any contributor want this feature, may will support this feature.

And welcome to contribute this.

**Comment by EINDEX** [comment]
Close by #16, Thanks @zhaochunqi's contribute.
