### ISSUE TITLE
After using this plugin, Logseq becomes very laggy and sometimes even gets stuck.

### ISSUE THREAD

**Issue by moulai** [EINDEX/logseq-memos-sync#7]
- OS: MacOS 13.2 (22D49)
- Logseq Version: v0.8.18
- Plugin Version: v1.3.1
- Issue Description: After enabling this plugin, the running speed of Logseq will become very slow and there will be lag. The specific steps to reproduce are as follows:
1. Install a brand new Logseq (to avoid interference from other issues and settings).
2. Create a new Graph.
3. Install plugins. My settings are to automatically sync every hour, auto-sync when Logseq is opened, and Memos synced to Logseq will not be archived.
4. Wait for the synchronization to complete. I have about 300+ Memos distributed over 150+ days.
5. After synchronization is complete, restart Logseq (to avoid interference from other issues).
6. Upon restarting, Logseq becomes very laggy. For example, when I enter the [[Memos]] page **(loading speed is slow)**, click on a #Tag label **(loading speed is slow)**, or return to the homepage by clicking on the Home button in the navigation bar **(this may cause it to freeze up or even become unresponsive)**, everything becomes slow or laggy.
7. Close the plugin, restart Logseq, and repeat step six; at this point everything runs quickly and smoothly indicating **that it's not due to problems with page quantity or block quantity etc**.
8. I also tried rebuilding indexes, clearing caches, refreshing etc., all of which did not solve the problem.

In Chinese:
1. 安装一个全新的Logseq（以避免其它问题和设置的干扰）。
2. 创建一个新的Graph。
3. 安装插件。我的设置是，每小时自动同步、在开启Logseq时自动同步、同步到Logseq的Memos不会归档。
4. 等待同步完成。我的Memos大约有300多条，分布在150多天中。
5. 同步完成后，重启Logseq（以避免其它问题干扰）。
6. 再次启动后，Logseq会变得很卡顿。例如，当我进入页面[[Memos]]**（加载速度很慢）**，点击某个标签#Tag **（加载速度很慢）**，再从导航栏点击Home按钮返回主页 **（此时可能会卡住，有时甚至整个Logseq都会无响应）**，都会变得很慢或者卡顿。
7. 关闭插件，重启Logseq，再进行第六步的操作，此时，一切都快速而顺畅。说明不是由于页面数量、块数量等问题导致的。
8. 我也尝试了在开启插件时，重建索引、清理缓存、刷新等操作，都无法解决问题。

**Comment by EINDEX** [comment]
@moulai change the sync logic, it will use less bandwidth and performance, cloud you try that one?

**Comment by moulai** [comment]
> @moulai change the sync logic, it will use less bandwidth and performance, cloud you try that one?

Okay! Thank you for your hard work. I will conduct the test as soon as possible!

**Comment by moulai** [comment]
@EINDEX  Great! The problem is solved.
I created a new Graph and then synchronized all the Memos. Now, switching between different Memo tags has become very smooth. Then I switched back to the homepage, unfortunately Logseq got stuck again and my computer started buzzing. However, I forced quit Logseq and restarted it, and everything was fine. There are no more problems now!
