### ISSUE TITLE
After sync to logseq from memos, the empty space of code block are lost.

### ISSUE THREAD

**Issue by qyzhizi** [EINDEX/logseq-memos-sync#8]
memos 中：
![image](https://user-images.githubusercontent.com/25292861/231338476-debec8dc-aa23-4585-be9c-569985e76ebd.png)
logseq 中：
![image](https://user-images.githubusercontent.com/25292861/231339969-b4eee7bb-b6e0-4e03-982a-5eb341823321.png)

**Comment by EINDEX** [comment]
This issue RCA is not memos-sync plugin, please follow up https://github.com/logseq/logseq/issues/9155 issue at logseq side.
